In [4]:
import numpy as np
import pandas as pd

In [5]:
import random

In [7]:
A = np.random.rand(100,30)
A

array([[0.36565738, 0.14946256, 0.99673426, ..., 0.62645603, 0.47632445,
        0.55876725],
       [0.78216186, 0.14049571, 0.06785426, ..., 0.11332261, 0.77530511,
        0.64763176],
       [0.24114263, 0.79577986, 0.68926188, ..., 0.68227948, 0.60335223,
        0.70814967],
       ...,
       [0.12029474, 0.75797384, 0.66353292, ..., 0.98468854, 0.77101389,
        0.16836491],
       [0.81764597, 0.5750328 , 0.3758418 , ..., 0.96215776, 0.5401657 ,
        0.69826223],
       [0.36971632, 0.20700701, 0.75256585, ..., 0.68979463, 0.62479975,
        0.20811031]])

In [9]:
from sklearn.decomposition import TruncatedSVD

In [10]:
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
svd

TruncatedSVD(n_components=5, n_iter=7, random_state=42)

In [11]:
svd.fit(A)

TruncatedSVD(n_components=5, n_iter=7, random_state=42)

In [17]:
# svd.transform(A)

### SVD manually

In [40]:
A_tr = A.transpose()

In [41]:
Z1 = np.matmul(A, A_tr) #Covariance matrix w.r.t rows
Z2 = np.matmul(A_tr, A) #Covariance matrix w.r.t columns

In [42]:
eigenvalues_z1, eigenvectors_z1 = np.linalg.eig(Z1)
eigenvalues_z2, eigenvectors_z2 = np.linalg.eig(Z2)

In [43]:
U = eigenvectors_z1
V = eigenvectors_z2

In [44]:
V.shape

(30, 30)

In [45]:
V_tr = V.transpose()

In [59]:
# PCA level transformation => T(100, 30) matmul(A(100, 30), V(30, 30))
T1 = np.matmul(A, V)
T1.shape

(100, 30)

In [ ]:
# A = U * Sigma * V_tr
# A(100,30) = U(100,100) * Sigma(100, 30) * V_tr(30, 30)

In [66]:
import math
Sigma = np.zeros((100,30))
incr = 0
for j in range(Sigma.shape[1]):
    Sigma[j][j] = math.sqrt(eigenvalues_z1[incr])
    incr = incr + 1
# Sigma

c:\users\vishal waghmare\3d objects\vscode_codes\github\machine_learning\ml_env\lib\site-packages\ipykernel_launcher.py:5: ComplexWarning: Casting complex values to real discards the imaginary part
  """


In [67]:
# Another method for projection
# T(100, 30) = matmul( U(100, 100) , Sigma(100, 30) )
T2 = np.matmul(U, Sigma)
T2.shape

(100, 30)

In [31]:
eigenvalues_z1.shape

(30,)

In [32]:
eigenvalues_z2.shape

(100,)

In [71]:
T1

array([[-2.48269705,  0.11864884,  0.23708242, ..., -0.00915263,
        -0.17109469,  0.20246468],
       [-2.52991243,  0.44615553, -0.41573075, ..., -0.06966266,
         0.25425554,  0.02508129],
       [-2.92368596, -0.03217852,  0.02466447, ...,  0.37907249,
        -0.28211354, -0.08123644],
       ...,
       [-2.69961727,  0.20400857, -0.07498133, ...,  0.18278289,
        -0.26900215,  0.27402947],
       [-3.13817016,  0.44984283, -0.96587483, ...,  0.06465047,
         0.12153973, -0.46955256],
       [-2.69873759,  0.25621958, -0.18267985, ...,  0.23894656,
        -0.44779311,  0.02327546]])

In [72]:
T2.real

array([[-2.48269705e+00,  1.18648839e-01, -2.37082422e-01, ...,
         9.15262930e-03,  1.23454506e-01, -3.53334329e-05],
       [-2.52991243e+00,  4.46155533e-01,  4.15730746e-01, ...,
         6.96626627e-02, -4.01387492e-01,  1.88166966e-01],
       [-2.92368596e+00, -3.21785209e-02, -2.46644655e-02, ...,
        -3.79072491e-01, -1.17499517e-01,  9.54399929e-02],
       ...,
       [-2.69961727e+00,  2.04008570e-01,  7.49813327e-02, ...,
        -1.82782889e-01,  1.10826321e-02,  2.62716847e-01],
       [-3.13817016e+00,  4.49842832e-01,  9.65874834e-01, ...,
        -6.46504706e-02,  6.18247819e-02,  1.81754492e-01],
       [-2.69873759e+00,  2.56219583e-01,  1.82679855e-01, ...,
        -2.38946562e-01,  3.20588642e-01,  7.87047425e-03]])

In [81]:
# suppose to be identity
np.matmul(U, U.transpose()).real

array([[ 0.80428473, -0.04614432, -0.03321611, ..., -0.02427458,
        -0.05521853, -0.03847857],
       [-0.04614432,  0.29077574,  0.00400276, ..., -0.02849157,
         0.07383869, -0.05118342],
       [-0.03321611,  0.00400276,  1.02452878, ...,  0.00878001,
        -0.01585546,  0.05724994],
       ...,
       [-0.02427458, -0.02849157,  0.00878001, ...,  0.73808043,
        -0.04704001, -0.01211329],
       [-0.05521853,  0.07383869, -0.01585546, ..., -0.04704001,
         0.73424054,  0.00685366],
       [-0.03847857, -0.05118342,  0.05724994, ..., -0.01211329,
         0.00685366,  0.65516137]])

In [76]:
# suppose to be identity
np.matmul(V, V.transpose())

array([[ 1.00000000e+00,  4.28650171e-15, -8.46545056e-16,
         3.09864981e-15, -5.18508847e-15, -2.36334390e-15,
         1.90125693e-15,  2.44314118e-15, -3.41697157e-15,
        -4.02862422e-15,  4.63214536e-15, -4.66206934e-16,
         6.43484831e-15, -4.20670443e-15,  2.21697660e-15,
         4.96347755e-15,  7.62410968e-15, -4.34027814e-15,
        -3.84544827e-15,  1.63242900e-15, -4.92227786e-15,
        -6.96057795e-16, -6.28230107e-15, -5.60098842e-16,
        -7.31272681e-15,  1.03606360e-14, -1.47261760e-15,
         5.78617015e-15,  6.49437101e-17, -4.24703675e-15],
       [ 4.28650171e-15,  1.00000000e+00,  1.17857113e-14,
        -2.66280054e-15,  8.45851167e-15, -8.30151919e-15,
         6.51909082e-15, -4.14251966e-15, -5.72892428e-15,
        -7.23639898e-15, -4.33941078e-15,  3.76088050e-15,
         5.17598117e-16, -7.63278329e-16,  8.95117314e-15,
        -2.45289900e-15,  4.89192020e-16,  2.39391840e-16,
        -1.34996181e-14, -1.00939222e-15,  7.97972799e-

In [79]:
# original matrix A
s = np.matmul(U, Sigma).real
np.matmul(s, V.transpose()).real

array([[ 0.80461862,  0.53173262,  0.15843964, ...,  0.41240584,
         0.39495133,  0.62935398],
       [ 0.29206527,  0.87401898,  0.26971524, ...,  0.89045025,
         0.8274509 ,  0.06735394],
       [ 0.80260498,  0.33203893,  0.64037955, ...,  0.11077643,
         0.49995042,  0.64972717],
       ...,
       [ 1.19874151,  0.61668796,  0.81992858, ...,  0.55237378,
         0.3230901 , -0.00604345],
       [ 0.15967203,  0.89916042,  0.28875635, ...,  0.6764768 ,
         0.72872416,  0.58766026],
       [ 0.86572428,  0.13677917,  0.41179573, ...,  0.06022452,
         0.7272205 ,  1.10279062]])

In [80]:
A

array([[0.36565738, 0.14946256, 0.99673426, ..., 0.62645603, 0.47632445,
        0.55876725],
       [0.78216186, 0.14049571, 0.06785426, ..., 0.11332261, 0.77530511,
        0.64763176],
       [0.24114263, 0.79577986, 0.68926188, ..., 0.68227948, 0.60335223,
        0.70814967],
       ...,
       [0.12029474, 0.75797384, 0.66353292, ..., 0.98468854, 0.77101389,
        0.16836491],
       [0.81764597, 0.5750328 , 0.3758418 , ..., 0.96215776, 0.5401657 ,
        0.69826223],
       [0.36971632, 0.20700701, 0.75256585, ..., 0.68979463, 0.62479975,
        0.20811031]])